### PR TITLE
Add Contrib support for Inverter Heat Pump such as Fairland IPHR55

### PR DESCRIPTION
**Pull request by valentindusollier**
This adds support for Inverter Heat Pump such as Fairland Inverter+ 21kW (IPHR55).

### CODE REVIEW

**Comment by valentindusollier** [comment]
I made the dotenv module optional. It is only use in `/testcontrib.py` in order to load environment variables from .env file. However it's not really needed. Moreover, this module is not installed in the workflows.

**Comment by uzlonewolf** [comment]
I do like the idea, but unfortunately python-dotenv only supports Python v3.8+ which is a bit too restrictive.  At some point we should probably rework the whole contrib test system to add tests like this for the other contrib modules as well.

**Comment by valentindusollier** [comment]
Yes, you're right. I think the right way to go for now is to remove it from `requirements.txt` and leave it as optional in `/testcontrib.py`. This way those who have the module installed can use it but `/testcontrib.py` works fine without `dotenv` as well. What do you think ?

**Comment by uzlonewolf** [comment]
Yes, that sounds good.

**Comment by valentindusollier** [comment]
Done ✅

**Comment by jasonacox** [comment]
Thanks @valentindusollier !

**Pull request merged**
