### PR TITLE
Standardize indentation for code snippets in the README.

### PR DESCRIPTION
**Pull request by TheOnlyWayUp**
From what I noticed while reading the README,
- Short Python and Bash Snippets have no Indentation
- Longer Python Snippets have 4 Spaces (`    `) of indentation

I did my best to judge what would be considered long/short and added indentation accordingly, but there is a clear lack of standardization with the indentation for snippets, I'd suggest removing indentation completely, to make copy pasting easier :)

By indentation, I mean the spaces added to the start of a line but not for Python's sake
```py
    import tinytuya
```
vs
```py
import tinytuya
```

---------

Thanks for the great project, everything is extremely well documented in the README and setting things up was a breeze \<3

### CODE REVIEW

**Comment by TheOnlyWayUp** [comment]
Please keep in mind, this pull request to bring more attention to this issue. It may not add indentation as you envisioned. I strongly suggest you rethink indentation for code snippets and possibly remove it altogether.

Thanks!

**Comment by jasonacox** [comment]
Hi @TheOnlyWayUp - thank you for this PR!  I completely agree with your points.  Let's remove the spaces.  Are you willing to do that and update the PR?  I would prefer you get the credit. 

Thanks for your help!

**Comment by TheOnlyWayUp** [comment]
> Are you willing to do that and update the PR? I would prefer you get the credit.

I'll do it within the next hour \:)

**Comment by TheOnlyWayUp** [comment]
@jasonacox Please take a look at [TheOnlyWayUp/tinytuya/patch-1/README.md](https://github.com/TheOnlyWayUp/tinytuya/blob/patch-1/README.md)

If everything is satisfactory, I think this pull request can be merged. Thanks for the cool library!

**Comment by jasonacox** [comment]
It looks so much better!!!  Thanks @TheOnlyWayUp !  Merged.

**Pull request merged**
