### PR TITLE
add set_socketRetryLimit(integer)

### PR DESCRIPTION
**Pull request by elfman03**
More for #2.  Extends #6 

Adds
set_socketRetryLimit(integer)      # retry count limit [default 5]

If retry limit is exceeded, the exception will be rethrown up to the client app.

to remove all retries set retry limit to 0 (or a negative number).  Will then see 10054 error on susceptible systems.

Error generating case for me:

```python
tuya.set_version(3.3)
#tuya.set_socketNODELAY(False)
#tuya.set_socketPersistent(True)
tuya.set_socketRetryLimit(0)
for i in range(2000):
    data=tuya.status()
    if(data['dps']['1']==False):
        print(str(i)+": off")
    else:
        print(str(i)+": on")
```

Working case for me is with the default 5 (I haven't seen more than like 2 retries under limited testing)

```python
tuya.set_version(3.3)
tuya.set_socketNODELAY(False)
tuya.set_socketPersistent(True)
#tuya.set_socketRetryLimit(0)
for i in range(2000):
    data=tuya.status()
    if(data['dps']['1']==False):
        print(str(i)+": off")
    else:
        print(str(i)+": on")
```

### CODE REVIEW

**Comment by jasonacox** [comment]
Thanks @elfman03  - Merged.

**Comment by arrmo** [comment]
Seeing this helping some errors I had as well, thanks! BTW, is this a limitation on the Tuya side (i.e. working around their responses)? Just curious 😄.

**Comment by jasonacox** [comment]
Thanks @arrmo - I'm curious, to help with the errors are you using these new options or just the defaults in the 1.0.5 version? 

```python
tuya.set_socketNODELAY(False) #default is True
tuya.set_socketPersistent(True)  #default is False
```

To be fair to Tuya, the Tuya based devices are really designed to be monitored and managed via the TuyaCloud.  For those of us who want to control them directly / locally, you need to decipher the protocol or use a tool like **tinytuya** to help. ;-)

**Comment by elfman03** [comment]
FYI, for me the retry=5 default made the biggest difference in preventing death. The persistent socket furthur dropped the number of times a retry is needed down but the retry was working ok even without the persistence.  The NODELAY, I'm not sure it helps one way or the other.  I am also curious what other people see with the persistence option.

**Comment by arrmo** [comment]
> are you using these new options or just the defaults in the 1.0.5 version?

Just using the defaults ... OK?

> For those of us who want to control them directly / locally, you need to decipher the protocol or use a tool like **tinytuya** to help. ;-)

Agreed! And thanks for this tool - much appreciated!

**Pull request merged**
